application: owlection
version: 1-4-5
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:

- url: /static
  static_dir: static

- url: /admin/.*
  script: controllers.admin.app

- url: /vote.*
  script: controllers.vote.app

- url: /authenticate/.*
  script: controllers.authenticate.app

- url: /tasks/.*
  script: controllers.tasks.app
  login: admin

- url: /intern/jobs-taskqueue
  script: controllers.intern.app
  login: admin

- url: /intern/.*
  script: controllers.intern.app

- url: /.*
  script: main.app
  secure: always
