application: owlection
version: 1-6-0
module: default
runtime: python27
api_version: 1
threadsafe: yes

instance_class: F2

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:

- url: /static
  static_dir: static

- url: /admin/.*
  script: controllers.admin.app

- url: /vote.*
  script: controllers.vote.app

- url: /authenticate/.*
  script: controllers.authenticate.app

- url: /intern/.*
  script: controllers.intern.app

- url: /api/.*
  script: controllers.api.app

- url: /.*
  script: main.app
  secure: always
